# Generated by Django 2.1.5 on 2019-02-03 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resume', models.FileField(upload_to='forhired-resumes')),
                ('date_posted', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
