# Generated by Django 2.1.5 on 2019-02-02 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='user',
        ),
        migrations.AddField(
            model_name='company',
            name='name',
            field=models.CharField(default='LunarStack', max_length=64),
            preserve_default=False,
        ),
    ]
